# Args: <cam_file> <obj_file> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {
        "global": {
          "output_dir": "<args:2>"
        }
      }
    },
    {
      "module": "loader.ObjectLoader",
      "config": {
        "path": "<args:1>"
      }
    },
    {
      "module": "lighting.LightSampler",
      "config": {
        "lights": [
          {
            "location": {
              "provider": "sampler.Shell",
              "center": [1, 2, 3],
              "radius_min": 4,
              "radius_max": 7,
              "elevation_min": 15,
              "elevation_max": 70
            },
            "type": "POINT",
            "energy": 500
          }
        ]
      }
    },
    {
      "module": "camera.CameraLoader",
      "config": {
        "path": "<args:0>",
        "file_format": "location rotation/value"
      }
    },
    {
      "module": "writer.ObjectStateWriter"
    },
    {
      "module": "writer.LightStateWriter"
    },
    {
      "module": "writer.CameraStateWriter"
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
      }
    },
    {
      "module": "writer.Hdf5Writer",
      "config": {
      }
    }
  ]
}
