# Args: <path_to_bop_data> <bop_datset_name> <bop_toolkit_path> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py",
      "scikit-image",
      "pypng==0.0.20",
      "scipy",
      "matplotlib",
      "pytz"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "<args:3>",
          "sys_paths": ["<args:2>"] # path to the bop toolkit
        }
      }
    },
    {
      "module": "loader.BopLoader",
      "config": {
        "bop_dataset_path": "<args:0>/<args:1>",
        "mm2m": True,
        "split": "val",
        "obj_ids": [1,1,3],
        "model_type": ""
      }
    },
    {
      "module": "lighting.LightSampler",
      "config": {
        "lights": [
          {
            "location": {
              "provider": "sampler.Shell",
              "center": [0, 0, -0.8],
              "radius_min": 1,
              "radius_max": 4,
              "elevation_min": 40,
              "elevation_max": 89
            },
            "type": "POINT",
            "energy": 1000
          }
        ]
      }
    },
    {
      "module": "composite.CameraObjectSampler",
      "config": {
        "total_noof_cams": 10,
        "noof_cams_per_scene": 5,
        "object_pose_sampler": {
          "module": "object.ObjectPoseSampler",
          "config": {
            "max_iterations": 1000,
            "pos_sampler": {
              "provider": "sampler.Uniform3d",
              "max": [0.2, 0.2, 0.2],
              "min": [-0.2, -0.2, -0.2]
            },
            "rot_sampler": {
              "provider": "sampler.Uniform3d",
              "max": [0, 0, 0],
              "min": [6.28, 6.28, 6.28]
            }
          }
        },
        "camera_pose_sampler": {
          "module": "camera.CameraSampler",
          "config": {
            "cam_poses": [
              {
                "location": {
                  "provider": "sampler.Shell",
                  "center": [0, 0, 0],
                  "radius_min": 1,
                  "radius_max": 1.2,
                  "elevation_min": 1,
                  "elevation_max": 89
                },
                "rotation": {
                  "format": "look_at",
                  "value": {
                    "provider": "getter.POI",
                    "parameters": {}
                  }
                }
              }
            ]
          }
        }
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "samples": 50,
        "render_distance": True
      }
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {
        "map_by": ["instance", "class", "cp_bop_dataset_name"],
        "default_values": {"class":0, "cp_bop_dataset_name": "None"}
      }
    },
    {
      "module": "writer.CocoAnnotationsWriter",
      "config": {
        "supercategory": "<args:1>",
        "append_to_existing_output": True
      }
    },
    {
      "module": "writer.BopWriter",
      "config": {
        "dataset": "<args:1>",
        "append_to_existing_output": True,
        "depth_scale": 1.0,
        "postprocessing_modules": {
          "distance": [
            {"module": "postprocessing.Dist2Depth"}
          ]
        }
      }
    }
  ]
}
