# Args: <cam_file> <obj_file> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {
        "global": {
          "output_dir": "<args:2>"
        }
      }
    },
    {
      "module": "loader.SuncgLoader",
      "config": {
        "path": "<args:1>"
      }
    },
    {
      "module": "camera.CameraLoader",
      "config": {
        "path": "<args:0>",
        "file_format": "location rotation/value _ _ _ _ _ _",
        "world_frame_change": ["X", "-Z", "Y"],
        "default_cam_param": {
          "rotation": {
            "format": "forward_vec"
          }
        }
      }
    },
    {
      "module": "lighting.SuncgLighting",
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {
        "use_alpha": True
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "use_alpha": True,
        "render_distance": true,
        "render_normals": True
      }
    },
    {
      "module": "writer.Hdf5Writer",
    }
  ]
}
