# Args: <path_to_shape-net-core> <obj_file> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "<args:2>"
        }
      }
    },
    {
      "module": "loader.SuncgLoader",
      "config": {
        "path": "<args:1>",
        "add_properties": {
          "cp_physics": False
        }
      }
    },
    {
      "module": "lighting.SuncgLighting",
      "config": {}
    },
    {
      "module": "loader.ShapeNetLoader",
      "config": {
        "data_path": "<args:0>",
        "used_synset_id": "02801938",
        "add_properties": {
          "cp_shape_net_object": True,
          # set the custom property physics to True
          "cp_physics": True
        }
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        # get all shape net objects, as we have only loaded one this returns only one entity
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "cp_shape_net_object": True,
            "type": "MESH"
          }
        },
        # Sets the location of this entity above a bed
        "location": {
          "provider": "sampler.UpperRegionSampler",
          "min_height": 0.75,
          "to_sample_on": {
              "provider": "getter.Entity",
              "conditions": {
                "cp_category_id": 1, # 1 is the category of the bed
                "type": "MESH"
              }

          }
        },
        # by adding a modifier we avoid that the objects falls through other objects during the physics simulation
        "cf_add_modifier": {
          "name": "Solidify",
          "thickness": 0.001
        }
      }
    },
    {
      "module": "object.PhysicsPositioning",
      "config": {
        "min_simulation_time": 0.5,
        "max_simulation_time": 4,
        "check_object_interval": 0.25,
        "mass_scaling": True,
        "mass_factor": 2000,
        "collision_margin": 0.0001
      }
    },
    {
      "module": "camera.CameraSampler",
      "config": {
        "cam_poses": [
        {
          "number_of_samples": 5,
          "location": {
            "provider":"sampler.PartSphere",
            "center": {
              "provider": "getter.POI",
              "selector": {
                "provider": "getter.Entity",
                "conditions": {
                  "cp_shape_net_object": True,
                  "type": "MESH"
                }
              }
            },
            "distance_above_center": 0.5,
            "radius": 2,
            "mode": "SURFACE"
          },
          "rotation": {
            "format": "look_at",
            "value": {
              "provider": "getter.POI",
              "selector": {
                "provider": "getter.Entity",
                "conditions": {
                  "cp_shape_net_object": True,
                  "type": "MESH"
                }
              }
            }
          }
        }
        ]
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors",
        "samples": 150,
        "render_distance": True,
        "render_normals": True
      }
    },
    {
      "module": "writer.Hdf5Writer",
      "config": {
        "postprocessing_modules": {
          "distance": [
          {
            "module": "postprocessing.TrimRedundantChannels",
          }
          ]
        }
      }
    }
  ]
}
