# Args: <path_to_shape-net-core> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py", "torch==1.8.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html", "git+https://github.com/abahnasy/smplx", "git+https://github.com/abahnasy/human_body_prior"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "<args:1>"
        }
      }
    },
    {
      "module": "loader.AMASSLoader",
      "config": {
        "data_path": "<args:0>",
        "sub_dataset_id": "CMU",
        "body_model_gender": "male",
        "subject_id": "10",
        "sequence_id": "1",
        "frame_id": "600",
      },
      
    },
    {
      "module": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "POINT",
            "location": [5, -5, 5],
            "energy": 1000
          }
        ]
      }
    },
    {
      "module": "camera.CameraSampler",
      "config": {
        "cam_poses": [
          {
            "number_of_samples": 5,
            "location": {
              "provider":"sampler.Sphere",
              "center":[0, 0, 0],
              "radius": 3,
              "mode": "SURFACE"
            },
            "rotation": {
              "format": "look_at",
              "value": {
                "provider": "getter.POI"
              }
            }
          }
        ]
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "render_normals": True,
        "samples": 350,
        "render_distance": true
      }
    },
    {
      "module": "writer.Hdf5Writer",
      "config": {
        "postprocessing_modules": {
          "distance": [
            {
              "module": "postprocessing.TrimRedundantChannels",
              "config": {}
            }
          ]
        }
      }
    }
  ]
}
