# Args: <obj_file> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {
        "global": {
          "output_dir": "<args:1>"
        }
      }
    },
    {
      "module": "loader.SuncgLoader",
      "config": {
        "path": "<args:0>"
      }
    },
    {
      "module": "camera.SuncgCameraSampler",
      "config": {
        "cam_poses": [{
          "number_of_samples": 10,
          "proximity_checks": {
            "min": 1.0
          },
          "min_interest_score": 0.4,
          "location": {
            "provider":"sampler.Uniform3d",
            "max":[0, 0, 2],
            "min":[0, 0, 0.5]
          },
          "rotation": {
            "value": {
              "provider":"sampler.Uniform3d",
              "max":[1.2217, 0, 6.283185307],
              "min":[1.2217, 0, 0]
            }
          },
        }]
      }
    },
    {
      "module": "lighting.SuncgLighting",
      "config": {}
    },
    {
      "module": "writer.CameraStateWriter",
      "config": {
        "attributes_to_write": ["location", "rotation_euler", "fov_x", "fov_y", "customprop_room_id"]
      }
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {
        "use_alpha": True
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "render_distance": True,
        "render_normals": True,
        "use_alpha": True
      }
    },
    {
      "module": "writer.Hdf5Writer",
    }
  ]
}
