# Args: <obj_file> <obj_file> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {
        "global": {
          "output_dir": "<args:2>"
        }
      }
    },
    {
      "module": "loader.SuncgLoader",
      "config": {
        "path": "<args:0>"
      }
    },
    {
      "module": "loader.ObjectLoader",
      "config": {
          "path": "<args:1>",
          "add_properties": {
            "cp_replace": "chair",
          }
        },
    },
    {
      "module": "object.ObjectReplacer",
      "config": {
        "replace_ratio": 1,
        "copy_properties": True,
        "objects_to_be_replaced": {
            "provider": "getter.Entity",
            "conditions": {
              "cp_coarse_grained_class": "chair",
              "type": "MESH"
            }
        },
        "objects_to_replace_with": {
            "provider": "getter.Entity",
            "conditions": {
              "cp_replace": "chair",
              "type": "MESH"
            }
        },
        "ignore_collision_with": {
          "provider": "getter.Entity",
            "conditions": {
              "cp_type": "Floor",
              "type": "MESH"
            }
        },
        "relative_rotation_sampler": {
          "provider": "sampler.Uniform3d",
          "max": [0, 0, 6.283185307],
          "min": [0, 0, 0]
        }
      }
    },
    {
      "module": "camera.SuncgCameraSampler",
      "config": {
        "cam_poses": [{
          "number_of_samples": 10,
          "proximity_checks": {
            "min": 1.0
          },
          "min_interest_score": 0.4,
          "location": {
            "provider":"sampler.Uniform3d",
            "max":[0, 0, 2],
            "min":[0, 0, 0.5]
          },
          "rotation": {
            "value": {
              "provider":"sampler.Uniform3d",
              "max":[1.2217, 0, 6.283185307],
              "min":[1.2217, 0, 0]
            }
          },
        }]
      }
    },
    {
      "module": "lighting.SuncgLighting",
      "config": {}
    },
    {
      "module": "writer.CameraStateWriter",
      "config": {
        "attributes_to_write": ["location", "rotation_euler", "fov_x", "fov_y", "customprop_room_id"]
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "render_normals": True,
        "render_distance": True,
        "use_alpha": True
      }
    },
    {
      "module": "writer.Hdf5Writer",
    }
  ]
}
