# Args: <obj_file> <texture_file> <cctexture folder> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "<args:3>",
          "max_bounces": 200,
          "diffuse_bounces": 200,
          "glossy_bounces": 200,
          "transmission_bounces": 200,
          "transparency_bounces": 200
        }
      }
    },
    {
      "module": "loader.SceneNetLoader",
      "config": {
        "file_path": "<args:0>",
        "texture_folder": "<args:1>"
      }
    },
    {
      "module": "loader.CCMaterialLoader",
      # you can use the scripts/download_cc_textures.py to download them
      "config": {
        "folder_path": "<args:2>",
        "preload": True
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "type": "MESH"
          }
        },
        "cf_randomize_materials": {
          "randomization_level": 0.4,
          "materials_to_replace_with": {
            "provider": "getter.Material",
            "random_samples": 1,
            "conditions": {
              "cp_is_cc_texture": True  # this will return one random loaded cc textures
            }
          }
        }
      }
    },
    {
      "module": "loader.CCMaterialLoader",
      # you can use the scripts/download_cc_textures.py to download them
      "config": {
        "folder_path": "<args:2>",
        "fill_used_empty_materials": True
      }
    },
    {
      "module": "camera.CameraSampler",
      "config": {
        "cam_poses": [{
          "number_of_samples": 5,
          "proximity_checks": {
            "min": 1.0
          },
          "location": {
            "provider": "sampler.UpperRegionSampler",
            "min_height": 1.5,
            "max_height": 1.8,
            "to_sample_on": {
              "provider": "getter.Entity",
              "conditions": {
                "cp_category_id": 2
              }
            }
          },
          "rotation": {
            "value": {
              "provider":"sampler.Uniform3d",
              "max":[1.2217, 0, 6.283185307],
              "min":[1.2217, 0, 0]
            }
          },
          "check_if_pose_above_object_list": {
            "provider": "getter.Entity",
            "check_empty": True,
            "conditions": {
              "cp_category_id": 2,
              "type": "MESH"
            }
          }
        }]
      }
    },
    {
      "module": "object.FloorExtractor",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "check_empty": True,
          "conditions": {
            "cp_category_id": 1
          }
        }, # this one you need to now beforehand
        "compare_angle_degrees" : 7.5,
        "compare_height": 0.15,
        "name_for_split_obj": "floor",  # this is the new name of the object
        "add_properties": {
          "cp_category_id": 2
        },
        "should_skip_if_object_is_already_there": True
      }
    },
    {
      "module": "object.FloorExtractor",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "check_empty": True,
          "conditions": {
            "cp_category_id": 1
          }
        },
        "up_vector_upwards": False,  # the polygons are now facing downwards: [0, 0, -1]
        "compare_angle_degrees": 7.5,
        "compare_height": 0.15,
        "add_properties": {
          "cp_category_id": 22
        },
        "name_for_split_obj": "ceiling",
        "should_skip_if_object_is_already_there": True
      }
    },
    {
      "module": "lighting.SurfaceLighting",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "check_empty": True,
          "conditions": {
            "name": ".*[l|L]amp.*"
          }
        },
        "emission_strength": 15.0
      }
    },
    {
      "module": "lighting.SurfaceLighting",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "check_empty": True,
          "conditions": {
            "name": ".*[c|C]eiling.*"
          }
        },
        "emission_strength": 2.0,
        "emission_color": [1, 1, 1, 1]
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "samples": 350,
        "render_normals": True,
        "render_distance": True,
      }
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {
        "use_alpha": true
      }
    },
    {
      "module": "writer.Hdf5Writer",
      "config": {
        "postprocessing_modules": {
          "distance": [
            {
              "module": "postprocessing.TrimRedundantChannels",
            }
          ]
        }
      }
    }
  ]
}
