# Args: <path_to_the_replica_data_folder>  <output_path>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py",
      "scikit-learn"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {
        "global": {
          "output_dir": "<args:1>",
          "data_set_name": "office_1",
          "data_path": "<args:0>"
        }
      }
    },
    {
      "module": "loader.ReplicaLoader",
      "config": {
        "use_smooth_shading": True
      }
    },
    {
      "module": "object.FloorExtractor",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "mesh"
          }
        },
        "compare_angle_degrees" : 7.5, # max angle difference to up facing polygons
        "compare_height": 0.15,   # height, which is allowed for polygons to be away from the height level in up and down dir.
        "name_for_split_obj": "floor"
      }
    },
    {
      "module": "camera.ReplicaCameraSampler",
      "config": {
        "is_replica_object": True,
        "cam_poses": [{
          "number_of_samples": 15,
          "clip_start": 0.01,
          "proximity_checks": {
            "min": 1.0,
            "avg": {
              "min": 2.0,
              "max": 4.0
            }
          },
          "location": [0, 0, 1.55],
          "rotation": {
            "value": {
              "provider":"sampler.Uniform3d",
              "max":[1.373401334, 0, 6.283185307],
              "min":[1.373401334, 0, 0]
            }
          },
        }]
      }
    },
    {
      "module": "manipulators.MaterialManipulator",
      "config": {
        "selector": {
          "provider": "getter.Material",
          "conditions": {
            "name": "ply_material"
          }
        },
        "cf_change_to_vertex_color_no_shading": "Col"
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "render_normals": True
      }
    },
    {
      "module": "writer.Hdf5Writer",
    }
  ]
}
