# Args: <obj_file> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {
        "global": {
          "output_dir": "<args:1>",
          "max_bounces": 200,
          "diffuse_bounces": 200,
          "glossy_bounces": 200,
          "transmission_bounces": 200,
          "transparency_bounces": 200
        }
      }
    },
    {
      "module": "loader.SuncgLoader",
      "config": {
        "path": "<args:0>"
      }
    },
    {
      "module": "camera.SuncgCameraSampler",
      "config": {
        "cam_poses": [{
          "number_of_samples": 10,
          "proximity_checks": {
            "min": 1.0
          },
          "min_interest_score": 0.4,
          "location": {
            "provider":"sampler.Uniform3d",
            "max":[0, 0, 1.85],
            "min":[0, 0, 1.65]
          },
          "rotation": {
            "value": {
              "provider":"sampler.Uniform3d",
              "max":[1.2217, 0, 6.283185307],
              "min":[1.2217, 0, 0]
            }
          },
        }]
      }
    },
    {
      "module": "lighting.SuncgLighting",
    },
    {
      "module": "manipulators.MaterialManipulator",
      "config": {
        "selector": {
          "provider": "getter.Material",
          "conditions": [
            {"name": "wood.*"},
            {"name": "laminate.*"},
            {"name": "beam.*"}
          ]
        },
        "cf_set_Roughness": {
           "provider": "sampler.Value",
           "type": "float",
           "min": 0.05,
           "max": 0.5,
        },
        "cf_set_Specular": {
          "provider": "sampler.Value",
          "type": "float",
          "min": 0.5,
          "max": 1,
        },
        "cf_color_link_to_displacement": {
          "provider": "sampler.Value",
          "type": "float",
          "min": 0.001,
          "max": 0.15,
        },
        "mode": "once_for_each"
      }
    },
    {
      "module": "manipulators.MaterialManipulator",
      "config": {
        "selector": {
          "provider": "getter.Material",
          "conditions": [
            { "name": "tile.*" },
            { "name": "brick.*" },
            { "name": "stone.*" }
          ]
        },
        "cf_set_Roughness": {
          "provider": "sampler.Value",
          "type": "float",
          "min": 0,
          "max": 0.2,
        },
        "cf_set_Specular": {
          "provider": "sampler.Value",
          "type": "float",
          "min": 0.9,
          "max": 1,
        },
        "mode": "once_for_each"
      }
    },
    {
      "module": "manipulators.MaterialManipulator",
      "config": {
        "selector": {
          "provider": "getter.Material",
          "conditions": [
          { "name": "carpet.*" },
          { "name": "textile.*" }
          ]
        },
        "cf_set_Roughness": {
          "provider": "sampler.Value",
          "type": "float",
          "min": 0.5,
          "max": 1.0,
        },
        "cf_set_Specular": {
          "provider": "sampler.Value",
          "type": "float",
          "min": 0.1,
          "max": 0.3,
        },
        "mode": "once_for_each"
      }
    },
    {
      "module": "writer.CameraStateWriter",
      "config": {
        "attributes_to_write": ["location", "rotation_euler", "fov_x", "fov_y", "customprop_room_id"]
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "samples": 350,
        "render_distance": True,
        "render_normals": True,
        "use_alpha": True
      }
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {
        "use_alpha": True
      }
    },
    {
      "module": "writer.Hdf5Writer",
    }
  ]
}
