# Args: <obj_file> <path_to_textures> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py",
      "imageio"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {
        "global": {
            "output_dir": "<args:2>"
          }
      }
    },
    {
      "module": "loader.ObjectLoader",
      "config": {
        "path": "<args:0>"
      }
    },
    {
      "module": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "POINT",
            "location": [5, -5, 5],
            "energy": 1000
          }
        ]
      }
    },
    {
      "module": "camera.CameraLoader",
      "config": {
        "cam_poses": [
        {
          "location": [0, -13.741, 4.1242],
          "rotation": {
            "value":[1.3, 0, 0]
          }
        },
        {
          "location": [1.9488, -6.5202, 0.23291],
          "rotation": {
            "value": [1.84, 0, 0.5]
          }
        }
        ]
      }
    },
    {
      "module": "manipulators.MaterialManipulator",
      "config": {
        "selector": {
          "provider": "getter.Material",
          "conditions": {
            "name": "Material.*"
          }
        },
        "mode": "once_for_each",
        "cf_textures": {
          "Base Color": {
            "provider": "sampler.Path",
            "path": "<args:1>/material_manipulation_sample_texture*.jpg"
          }
        }
      }
    },
    {
      "module": "manipulators.MaterialManipulator",
      "config": {
        "selector": {
          "provider": "getter.Material",
          "conditions": {
            "name": "Material.001"
          }
        },
        "cf_color_link_to_displacement": 1.5
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors",
        "samples": 350
      }
    },
    {
      "module": "writer.Hdf5Writer",
    }
  ]
}
