# Args: <IKEA_PATH> <CC_TEXTURES> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "<args:2>",
          "max_bounces": 200,
          "diffuse_bounces": 200,
          "glossy_bounces": 200,
          "transmission_bounces": 200,
          "transparency_bounces": 200
        }
      }
    },
    {
      "module": "loader.CCMaterialLoader",
      "config": {
        "used_assets": ["Bricks", "Wood", "Carpet", "Tile", "Marble"],
        "folder_path": "<args:1>"
      }
    },
    {
      "module": "constructor.RandomRoomConstructor",
      "config": {
        "floor_area": 25,
        "amount_of_extrusions": 5,
        "used_loader_config": [
          {
            "module": "loader.IKEALoader",
            "config": {
              "data_dir": "<args:0>",
              "category": ["bed", "chair", "desk", "bookshelf"]
            },
            "amount_of_repetitions": 15
          },
        ]
      }
    },
    {
      "module": "lighting.SurfaceLighting",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "Ceiling"
          },
          "emission_strength": 4.0,
          "emission_color": [1, 1, 1, 1]
        }
      }
    },
    {
      "module": "camera.CameraSampler",
      "config": {
        "cam_poses": [{
          "number_of_samples": 5,
          "proximity_checks": {
            "min": 1.2
          },
          "location": {
            "provider": "sampler.UpperRegionSampler",
            "min_height": 1.5,
            "max_height": 1.8,
            "to_sample_on": {
              "provider": "getter.Entity",
              "index": 0,
              "conditions": {
                "name": "Floor",
                "type": "MESH"
              }
            }
          },
          "rotation": {
            "value": {
              "provider":"sampler.Uniform3d",
              "max":[1.4217, 0, 6.283185307],
              "min":[1.0, 0, 0]
            }
          },
          "min_interest_score": 0.4,
          "check_if_pose_above_object_list": {
            "provider": "getter.Entity",
            "conditions": {
              "name": "Floor",
              "type": "MESH"
            }
          }
        }]
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "samples": 350,
        "render_distance": True
      }
    },
    {
      "module": "writer.Hdf5Writer",
      "config": {
        "postprocessing_modules": {
          "distance": [
            {
              "module": "postprocessing.Dist2Depth",
            }
          ]
        }
      }
    }
  ]
}
